server:
  port: 13000

eureka:
  instance:
    hostname: eurekaServer13000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:   http://eurekaServer13002:13002/eureka/
  server:
    enable-self-preservation: false